try{
    if(2 == 2){
       abhi =  new Error('abhishek is the defined')
    //    throw abhi;
    }
    // console.log(abhi)
    throw new Error('')
}

// when the error is comes in the script then the catch  block will execute
catch(error){
    console.log(abhi)
}